### PR TITLE
remove Pipfile.lock from the generated code

### PR DESCRIPTION
**Pull request by AlmogCohen**
As recommended by the best practices of Pipenv [here](https://pipenv.readthedocs.io/en/latest/basics/#general-recommendations-version-control)

I believe that indded users of this cookiecutter should lock their versions on their own based on their projects.

### CODE REVIEW

**Comment by elgertam** [comment]
@AlmogCohen This one is a bit more debatable.

Since `cookiecutter` doesn't automatically add files to git and since the templated `Pipfile.lock` has no real content other than some internal `Pipenv` metadata, I'd like to discuss further. I originally set up the project the project such that it treated `Pipfile`'s contents as a stand-in for dependencies specified in `setup.py` and treated `Pipfile.lock`'s contents as a (more thorough) stand-in for `requirements.txt`. I was talked down from this based on an extended discussion with the Pipenv developers.

The take-away for me from that discussion is that the `Pipenv` developers envision `setup.py` as documenting the abstract package dependencies; `Pipfile` as documenting the actual concrete packages (with broad version specifiers) as they might be pulled from PyPI, a private registry or somewhere else; and `Pipfile.lock` being used to recreate an exact environment including a target Python version. The latter case seems only to apply to either developing applications or debugging "works on my machine" types of issues in library code.

From what I can tell, the vast majority of Pipenv users are building applications (although I personally think someone could develop libraries, too), and so having an empty Pipfile.lock would be useful for them. I know that for me, I start a new project thus:

```
$ cookiecutter gh:elgertam/cookiecutter-pipenv
# go through the prompts
...
$ cd newproj
$ git add .
$ git commit -m "Initial commit - project scaffolding"
```

My thinking (and I could be wrong) is that the minority of people using Pipenv for library development would either add `Pipfile.lock` to their `.gitignore` or simply delete it.

What are your thoughts?

**Comment by AlmogCohen** [comment]
Wait! I see now that the Pipfile.lock I removed was completely empty! For some reason I thought that it was full of frozen versions. Maybe I looked into the repo `Pipfile.lock` before deleting this file. Seeing that now, I agree that this PR is useless. Thank you for pointing that out again.

*IF* this was a fully calculated `Pipfile.lock` file I would have recommended to remove it, but it seems like you did the right thing to include an empty one. 

I agree with all of what you said above, and wanted to add on top of that, that this file would be re-created anyway the first time the user will run `pipenv install`

**Comment by AlmogCohen** [comment]
I'll just add that I'm building libraries on a regular basis and I do include the `pipenv` files to allow myself and other users to run the libraries in `dev` mode. `setup.py` is for `pypi` and `pip`, `pipenv` is for development and testing.

That's why I don't use the `python setup.py test` method anymore. I mix them both and do expect users who want to test my libraries to be able to run `pipenv install --dev` and even instruct them about it in the README files

**Comment by AlmogCohen** [comment]
Many times my `Pipfile` would include the `pipenv install -e .` so the current package is automatically installed from source when using `pipenv`. Just wanted to share how I use `pipenv` in libraries as you have brought it up :)

**Pull request closed without merging**
