### PR TITLE
Better Pipfile

### PR DESCRIPTION
**Pull request by PsiACE**
add `name = "pypi"` to 'source'.
add `cryptography` to `dev-packages`
delete `Pipfile.lock`

### CODE REVIEW

**Comment by elgertam** [comment]
@PsiACE Thank you for this PR. A couple things:

1. Can you rearrange the edits to the Pipfiles so that lines are not moved around?
2. Do you have a good argument for removing Pipfile.lock? I have debated keeping it out, but I keep it in since a plausible workflow involves running `git add .` immediately after running `cookiecutter`. The vast majority of the time, Pipfile.lock should be versioned, and the file is essentially empty when first generated.

If you can fix #1 and either undo the deletion or give me a good argument for why I shouldn't include the generated Pipfile.lock, I'll be happy to merge.

**Comment by PsiACE** [comment]
Thank you for your reply, this is some of my thoughts:
1. It’s just based on Pipenv’s default Pipfile template, I don’t think this is a problem.
2. I carefully considered your opinion and will make a small change later.

**Comment by PsiACE** [comment]
Ok, I re-added the `Pipfile.lock` file. 
In fact, I have considered modifying `post_gen_project.py`, but there are other factors to consider.

**Comment by PsiACE** [comment]
fixed #1

**Comment by PsiACE** [comment]
I got a new Pipfile.lock file, do you want to update it?

**Comment by PsiACE** [comment]
@elgertam  No more improvements for the time being, consider merging it?

**Comment by elgertam** [comment]
@PsiACE Thanks for the enthusiasm! I probably won't have time to review this for at least a week, but I'll get to it eventually (within a few weeks).

**Pull request merged**
